MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
RGBLIGHT_ENABLE = no
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
LTO_ENABLE = yes
OLED_ENABLE = yes
RGB_MATRIX_ENABLE = yes
# Enable framebuffer effects for the typing heatmap effect.
RGB_MATRIX_FRAMEBUFFER_EFFECTS = yes
VIA_ENABLE = yes